version: "3.9"
services:
  playground:
    build: .
    container_name: playground
    ports:
      - "8080:8080"
    networks:
      - playground-network
    environment:
      REDIS_HOST: redis-srv
    depends_on:
      - redis
  redis:
    image: redis
    container_name: redis-srv
    networks:
      - playground-network
networks:
  playground-network: